# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: motocatalogdb
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
    ports:
      - 3307:3306
    